# @author: MembaCo.
services:
  algo-dizibox-downloader:
    # Konteyner adını proje ile tutarlı hale getirelim
    image: ghcr.io/membaco/algo-video-downloader:main
    container_name: algo-dizibox-downloader # Konteyner adını proje ile tutarlı hale getirelim
    ports:
      - 5000:5000
    volumes:
      # Tüm kalıcı verileri (database, logs vb.) bu tek klasörde toplayalım.
      # Bu yol, config.py'deki DATA_DIR ile %100 uyumlu olmalı.
      - type: bind
        source: /DATA/AppData/algo-dizibox-downloader/data
        target: /app/data
      # İndirilen dosyalar için ayrı bir volume tanımı yapalım.
      - type: bind
        source: /DATA/AppData/algo-dizibox-downloader/downloads
        target: /app/downloads
    environment:
      - SECRET_KEY= # Buraya çok gizli ve rastgele bir anahtar yazın
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH= # Buraya ürettiğiniz parola hash'ini yapıştırın
      # DATA_DIR ortam değişkenini de buraya ekleyerek esneklik katabiliriz.
      - DATA_DIR=/app/data
    restart: unless-stopped
    shm_size: 2g
    # ... (x-casaos kısmı aynı kalabilir) ...
